// <auto-generated />
using System;
using CharacterManager.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CharacterManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251222214203_AddRoadmapNotes")]
    partial class AddRoadmapNotes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CharacterManager.Server.Models.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdultModeEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastImportedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastImportedFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("CharacterManager.Server.Models.Capacite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PersonnageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PersonnageId");

                    b.ToTable("Capacites");
                });

            modelBuilder.Entity("CharacterManager.Server.Models.HistoriqueEscouade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Classement")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateEnregistrement")
                        .HasColumnType("TEXT");

                    b.Property<string>("DonneesEscouadeJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PuissanceTotal")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("HistoriquesEscouade");
                });

            modelBuilder.Entity("CharacterManager.Server.Models.LucieHouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LucieHouses");
                });

            modelBuilder.Entity("CharacterManager.Server.Models.Personnage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Faction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrlDetailStored")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ImageUrlDetail");

                    b.Property<string>("ImageUrlHeader")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrlPreviewStored")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ImageUrlPreview");

                    b.Property<string>("ImageUrlSelectedStored")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ImageUrlSelected");

                    b.Property<int>("Niveau")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PV")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Puissance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rang")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rarete")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Selectionne")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeAttaque")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Personnages");
                });

            modelBuilder.Entity("CharacterManager.Server.Models.Piece", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AspectsStrategiques")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AspectsTactiques")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BonusStrategiquesSerialized")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("BonusStrategiques");

                    b.Property<string>("BonusTactiquesSerialized")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("BonusTactiques");

                    b.Property<int?>("LucieHouseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Niveau")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PuissanceLegacy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Puissance");

                    b.Property<bool>("Selectionnee")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LucieHouseId");

                    b.ToTable("Pieces");
                });

            modelBuilder.Entity("CharacterManager.Server.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AdultMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HashAlgorithm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LockoutUntil")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("CharacterManager.Server.Models.RoadmapNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RoadmapNotes");
                });

            modelBuilder.Entity("CharacterManager.Server.Models.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonnagesJson")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PuissanceTotal")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("CharacterManager.Server.Models.Capacite", b =>
                {
                    b.HasOne("CharacterManager.Server.Models.Personnage", null)
                        .WithMany("Capacites")
                        .HasForeignKey("PersonnageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CharacterManager.Server.Models.Piece", b =>
                {
                    b.HasOne("CharacterManager.Server.Models.LucieHouse", null)
                        .WithMany("Pieces")
                        .HasForeignKey("LucieHouseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CharacterManager.Server.Models.LucieHouse", b =>
                {
                    b.Navigation("Pieces");
                });

            modelBuilder.Entity("CharacterManager.Server.Models.Personnage", b =>
                {
                    b.Navigation("Capacites");
                });
#pragma warning restore 612, 618
        }
    }
}
