// <auto-generated />
using System;
using CharacterManager.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CharacterManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260124090000_AddDatesToHistoriqueModifications")]
    partial class AddDatesToHistoriqueModifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CharacterManager.Server.Models.HistoriqueModification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AncienneValeur")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChampModifie")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateInsertion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateMiseAJour")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("EntiteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomEntite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NouvelleValeur")
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeEntite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeModification")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DateModification");

                    b.ToTable("HistoriquesModifications");
                });
#pragma warning restore 612, 618
        }
    }
}
