// <auto-generated />
using System;
using CharacterManager.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CharacterManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CharacterManager.Server.Models.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdultModeEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastExportDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastImportedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastImportedFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("CharacterManager.Server.Models.Capacite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PersonnageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PersonnageId");

                    b.ToTable("Capacites");
                });

            modelBuilder.Entity("CharacterManager.Server.Models.Classement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HistoriqueClassementId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Valeur")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HistoriqueClassementId");

                    b.ToTable("Classement");
                });

            modelBuilder.Entity("CharacterManager.Server.Models.HistoriqueClassement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DateEnregistrement")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ligue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuissanceCommandant")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuissanceLucie")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuissanceMercenaires")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuissanceTotale")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("HistoriquesClassement");
                });

            modelBuilder.Entity("CharacterManager.Server.Models.HistoriqueLigue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DateMontee")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ligue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HistoriquesLigue");
                });

            modelBuilder.Entity("CharacterManager.Server.Models.HistoriqueModification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AncienneValeur")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChampModifie")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateInsertion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateMiseAJour")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("EntiteId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstImportation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomEntite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NouvelleValeur")
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeEntite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeModification")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DateModification");

                    b.ToTable("HistoriquesModifications");
                });

            modelBuilder.Entity("CharacterManager.Server.Models.LucieHouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Affection")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LucieHouses");
                });

            modelBuilder.Entity("CharacterManager.Server.Models.Personnage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<int>("Faction")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasRelation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrlDetailStored")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ImageUrlDetail");

                    b.Property<string>("ImageUrlHeader")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrlPreviewStored")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ImageUrlPreview");

                    b.Property<string>("ImageUrlSelectedStored")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ImageUrlSelected");

                    b.Property<int>("NivRelation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Niveau")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PV")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Puissance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rang")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rarete")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Selectionne")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeAttaque")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Personnages");

                    b.HasDiscriminator().HasValue("Personnage");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CharacterManager.Server.Models.PersonnageClassement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HistoriqueClassementAndroideId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HistoriqueClassementCommandantId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HistoriqueClassementMercenaireId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdOrigine")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Niveau")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Puissance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rang")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HistoriqueClassementAndroideId");

                    b.HasIndex("HistoriqueClassementCommandantId")
                        .IsUnique();

                    b.HasIndex("HistoriqueClassementMercenaireId");

                    b.ToTable("PersonnagesClassement");
                });

            modelBuilder.Entity("CharacterManager.Server.Models.Piece", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AspectsStrategiques")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AspectsTactiques")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BonusStrategiquesSerialized")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("BonusStrategiques");

                    b.Property<string>("BonusTactiquesSerialized")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("BonusTactiques");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LucieHouseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Niveau")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PuissanceLegacy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Puissance");

                    b.Property<bool>("Selectionnee")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LucieHouseId");

                    b.ToTable("Pieces");

                    b.HasDiscriminator().HasValue("Piece");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CharacterManager.Server.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AdultMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HashAlgorithm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LockoutUntil")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("CharacterManager.Server.Models.RoadmapNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RoadmapNotes");
                });

            modelBuilder.Entity("CharacterManager.Server.Models.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonnagesJson")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PuissanceTotal")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("CharacterManager.Server.Models.PersonnageHistorique", b =>
                {
                    b.HasBaseType("CharacterManager.Server.Models.Personnage");

                    b.Property<int>("HistoriqueClassementId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdOrigine")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("PersonnageHistorique");
                });

            modelBuilder.Entity("CharacterManager.Server.Models.PieceHistorique", b =>
                {
                    b.HasBaseType("CharacterManager.Server.Models.Piece");

                    b.Property<int>("HistoriqueClassementId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdOrigine")
                        .HasColumnType("INTEGER");

                    b.HasIndex("HistoriqueClassementId");

                    b.HasDiscriminator().HasValue("PieceHistorique");
                });

            modelBuilder.Entity("CharacterManager.Server.Models.Capacite", b =>
                {
                    b.HasOne("CharacterManager.Server.Models.Personnage", null)
                        .WithMany("Capacites")
                        .HasForeignKey("PersonnageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CharacterManager.Server.Models.Classement", b =>
                {
                    b.HasOne("CharacterManager.Server.Models.HistoriqueClassement", null)
                        .WithMany("Classements")
                        .HasForeignKey("HistoriqueClassementId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CharacterManager.Server.Models.PersonnageClassement", b =>
                {
                    b.HasOne("CharacterManager.Server.Models.HistoriqueClassement", null)
                        .WithMany("Androides")
                        .HasForeignKey("HistoriqueClassementAndroideId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CharacterManager.Server.Models.HistoriqueClassement", null)
                        .WithOne("Commandant")
                        .HasForeignKey("CharacterManager.Server.Models.PersonnageClassement", "HistoriqueClassementCommandantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CharacterManager.Server.Models.HistoriqueClassement", null)
                        .WithMany("Mercenaires")
                        .HasForeignKey("HistoriqueClassementMercenaireId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CharacterManager.Server.Models.Piece", b =>
                {
                    b.HasOne("CharacterManager.Server.Models.LucieHouse", null)
                        .WithMany("Pieces")
                        .HasForeignKey("LucieHouseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CharacterManager.Server.Models.PieceHistorique", b =>
                {
                    b.HasOne("CharacterManager.Server.Models.HistoriqueClassement", null)
                        .WithMany("Pieces")
                        .HasForeignKey("HistoriqueClassementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterManager.Server.Models.HistoriqueClassement", b =>
                {
                    b.Navigation("Androides");

                    b.Navigation("Classements");

                    b.Navigation("Commandant");

                    b.Navigation("Mercenaires");

                    b.Navigation("Pieces");
                });

            modelBuilder.Entity("CharacterManager.Server.Models.LucieHouse", b =>
                {
                    b.Navigation("Pieces");
                });

            modelBuilder.Entity("CharacterManager.Server.Models.Personnage", b =>
                {
                    b.Navigation("Capacites");
                });
#pragma warning restore 612, 618
        }
    }
}
